### ISSUE TITLE
Unable to get primary output

### ISSUE THREAD

**Issue by chrisduerr** [chrisduerr/leechbar#1]
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(PrimaryScreenInfoError(147), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.```

This happens on some broken i3 machine. It fails at `randr::get_output_info`. Fails at getting the primary screen info with no output set. Works when output is set manually.

**Comment by Ckath** [comment]
I think this is more a problem on the user's side

**Comment by forell** [comment]
Much good, very issue.

**Comment by chrisduerr** [comment]
It might be. But I'm just gonna keep it so others have a cenralized place to complain.

**Comment by chrisduerr** [comment]
This issue was recreated on a different system. It seems to be something that multiple systems have issues with.

This also only returns a `PrimaryScreenInfoError(148)`. Errors should be more descriptive. This error should be called `Unable to find primary screen`.

Running `xrandr --output <OUTPUT> --primary` solves the issue. So a primary output is not always setup with Xorg.

**Comment by chrisduerr** [comment]
This will probaby be resolved with #26
